package com.trendbench.global.exception;

public enum ErrorCode {
	INVALID_UPLOAD_REQUEST,
	EMPTY_FILE,
	INVALID_FILE_TYPE,
	INVALID_XLSX_FILE,
	MISSING_REQUIRED_SHEET,
	INVALID_DATA_BASIS_SHEET,
	MISSING_DATA_BASIS_VALUE,
	INVALID_REPORT_PERIOD,
	INVALID_AGGREGATION_UNIT,
	INVALID_CREDENTIAL,
	INVALID_TOKEN,
	EXPIRED_TOKEN,
	ACCESS_DENIED,
	USER_NOT_FOUND,
	EMAIL_ALREADY_EXISTS,
	INTERNAL_SERVER_ERROR
}
