package com.trendbench.global.exception;

public enum ErrorCode {
	INVALID_UPLOAD_REQUEST,
	EMPTY_FILE,
	INVALID_FILE_TYPE,
	INVALID_CREDENTIAL,
	INVALID_TOKEN,
	EXPIRED_TOKEN,
	ACCESS_DENIED,
	USER_NOT_FOUND,
	EMAIL_ALREADY_EXISTS,
	INTERNAL_SERVER_ERROR
}
